/**
 * build.js — Pixel Painter Studio
 *
 * Usage: node build.js
 *
 * Reads ui/index.html, inlines ui/styles.css and all JS modules as <style>/<script>
 * tags, escapes the result for a JS template literal, then prepends it as
 * `var UI_HTML = \`...\`` to the sandbox section of code.js.
 *
 * code.js structure (preserved between builds):
 *   // AUTO-GENERATED — do not edit above SANDBOX START
 *   var UI_HTML = `...inlined HTML...`;
 *
 *   // === SANDBOX START ===
 *   // Figma plugin sandbox code lives here — edit freely
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT    = __dirname;
const UI_DIR  = path.join(ROOT, 'ui');
const CODE_JS = path.join(ROOT, 'code.js');

// JS modules are concatenated in this order (order matters for variable scoping)
const JS_MODULES = [
  'canvas.js',
  'tools.js',
  'history.js',
  'colors.js',
  'export.js',
  'app.js',   // app.js last — it may call functions from modules above
];

const SANDBOX_MARKER = '// === SANDBOX START ===';

// ── Helpers ───────────────────────────────────────────────────────────────────

function readUI(filename) {
  const fp = path.join(UI_DIR, filename);
  if (!fs.existsSync(fp)) return '';
  return fs.readFileSync(fp, 'utf8');
}

function escapeForTemplateLiteral(str) {
  // Order matters: backslash first, then backtick, then ${
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

// ── Build UI HTML ─────────────────────────────────────────────────────────────

let html = readUI('index.html');
if (!html) {
  console.error('ERROR: ui/index.html not found.');
  process.exit(1);
}

// Inline CSS
const css = readUI('styles.css');
html = html.replace(
  '<!-- STYLES -->',
  css ? `<style>\n${css}\n</style>` : ''
);

// Inline JS modules
const scripts = JS_MODULES
  .map(f => {
    const src = readUI(f);
    return src ? `<script>\n// --- ${f} ---\n${src}\n</script>` : '';
  })
  .filter(Boolean)
  .join('\n');
html = html.replace('<!-- SCRIPTS -->', scripts);

const escapedHTML = escapeForTemplateLiteral(html);

// ── Read sandbox section from existing code.js ────────────────────────────────

let sandboxCode = '';

if (fs.existsSync(CODE_JS)) {
  const existing = fs.readFileSync(CODE_JS, 'utf8');
  const markerIdx = existing.indexOf(SANDBOX_MARKER);
  if (markerIdx !== -1) {
    sandboxCode = existing.slice(markerIdx);
  }
}

if (!sandboxCode) {
  console.error(
    'ERROR: code.js is missing or has no "' + SANDBOX_MARKER + '" marker.\n' +
    'Seed code.js with the marker before running build.js.'
  );
  process.exit(1);
}

// ── Write code.js ─────────────────────────────────────────────────────────────

const output = [
  '// AUTO-GENERATED by build.js — do not edit above the SANDBOX START marker',
  `var UI_HTML = \`${escapedHTML}\`;`,
  '',
  sandboxCode,
].join('\n');

fs.writeFileSync(CODE_JS, output, 'utf8');

const kb = (output.length / 1024).toFixed(1);
console.log(`✓  Built code.js  (${kb} KB)`);
console.log(`   UI modules : ${JS_MODULES.filter(f => readUI(f)).join(', ')}`);
console.log(`   Reload plugin in Figma to verify.`);
